# Generated by Django 3.0.5 on 2020-05-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('acid', models.AutoField(db_column='ACID', primary_key=True, serialize=False)),
                ('activity_name', models.CharField(db_column='ACTIVITY_NAME', max_length=50)),
            ],
            options={
                'db_table': 'ACTIVITIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('aid', models.AutoField(db_column='AID', primary_key=True, serialize=False)),
                ('status', models.BooleanField(db_column='STATUS')),
                ('attendance_datetime', models.DateTimeField(db_column='ATTENDANCE_DATETIME')),
            ],
            options={
                'db_table': 'ATTENDANCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('bid', models.AutoField(db_column='BID', primary_key=True, serialize=False)),
                ('bname', models.CharField(db_column='BNAME', max_length=25)),
            ],
            options={
                'db_table': 'BUILDING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.AutoField(db_column='DID', primary_key=True, serialize=False)),
                ('dname', models.CharField(db_column='DNAME', max_length=25)),
            ],
            options={
                'db_table': 'DEPARTMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DutyRostrum',
            fields=[
                ('drid', models.AutoField(db_column='DRID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DUTY_ROSTRUM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(db_column='EID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=20)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=20)),
                ('email', models.CharField(db_column='EMAIL', max_length=50)),
                ('phone_number', models.CharField(db_column='PHONE_NUMBER', max_length=15)),
                ('dob', models.DateField(db_column='DOB')),
            ],
            options={
                'db_table': 'EMPLOYEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('erid', models.AutoField(db_column='ERID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ERRORS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('rid', models.AutoField(db_column='RID', primary_key=True, serialize=False)),
                ('rname', models.CharField(db_column='RNAME', max_length=25)),
            ],
            options={
                'db_table': 'REGION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('sid', models.AutoField(db_column='SID', primary_key=True, serialize=False)),
                ('start_time', models.TimeField(db_column='START_TIME')),
                ('end_time', models.TimeField(db_column='END_TIME')),
            ],
            options={
                'db_table': 'SHIFT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('tid', models.AutoField(db_column='TID', primary_key=True, serialize=False)),
                ('tname', models.CharField(db_column='TNAME', max_length=25)),
            ],
            options={
                'db_table': 'TITLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'TITLE_VIOLATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='TYPE', max_length=25)),
            ],
            options={
                'db_table': 'UNIFORM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vioation',
            fields=[
                ('vid', models.AutoField(db_column='VID', primary_key=True, serialize=False)),
                ('vioation_name', models.CharField(db_column='VIOATION_NAME', max_length=50)),
                ('vioation_description', models.TextField(db_column='VIOATION_DESCRIPTION')),
            ],
            options={
                'db_table': 'VIOATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('wid', models.AutoField(db_column='WID', primary_key=True, serialize=False)),
                ('wages_type', models.CharField(db_column='WAGES_TYPE', max_length=25)),
            ],
            options={
                'db_table': 'WAGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zid', models.AutoField(db_column='ZID', primary_key=True, serialize=False)),
                ('zone_number', models.IntegerField(db_column='ZONE_NUMBER')),
            ],
            options={
                'db_table': 'ZONE',
                'managed': False,
            },
        ),
    ]
